name: supabase_helper
description: Generates Dart models/enums/functions from Supabase. Add annotation to your generated classes automatically.
version: 0.0.5
repository: https://github.com/raoul-m/supabase_helper

environment:
  sdk: ^3.6.1

dependencies:
  args: ^2.6.0
  path: ^1.8.0
  meta: ^1.15.0
  http: ^1.3.0
  yaml: ^3.1.3
  dart_style: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^5.0.0
  test: ^1.25.15

executables:
  supabase_helper: bin/supabase_helper.dart

